/**
 * The Ascension IT mark, from the client's supplied logo (public/brand/ascension-mark.png,
 * generated by scripts/gen-brand.mjs). The mark sits on white — the same surface the header and
 * the sign-in card use — so its negative space reads as the background.
 *
 * A plain <img> (not next/image): the asset is tiny and fixed-size, and this renders in server
 * components without configuration. `alt` is empty when a text wordmark sits beside it (the
 * wordmark carries the name); pass an explicit alt when the mark stands alone.
 */
export function BrandMark({ className, alt = '' }: { className?: string; alt?: string }) {
  // eslint-disable-next-line @next/next/no-img-element
  return <img src="/brand/ascension-mark.png" alt={alt} className={className} width={137} height={120} />
}
