-- --------------------------------------------------------------------------
-- 0001_seed_catalogue.sql -- 90 catalogue SKUs across 6 categories
--
-- GENERATED FILE. Do not edit by hand -- edit scripts/generate-seed.mjs and re-run
-- `npm run seed:generate`. The generator is deterministic (mulberry32, fixed seed
-- 20260819), so regenerating produces byte-identical output.
--
-- Apply after migrations 0001-0012, in the Supabase SQL editor.
-- Every statement is ON CONFLICT DO NOTHING, so re-running is safe.
--
-- The 9000-block is reserved for the pinned fixtures in 0002 and never appears here.
--
-- Contains no credentials of any kind. Timestamps are relative expressions, so the data is
-- correctly aged whenever the file is applied.
-- --------------------------------------------------------------------------


INSERT INTO public.products (sku, name, category, uom, low_stock_threshold) VALUES
  ('SEA-1016', 'Whitlock Low-Profile Brushed-Steel Bar Stool', 'Seating', 'EA', 19),
  ('SEA-1046', 'Ashgrove Two-Seat Sofa', 'Seating', 'EA', 25),
  ('SEA-1061', 'Halden Lounge Chair', 'Seating', 'EA', 8),
  ('SEA-1096', 'Quillon Swivel Felt-Panelled Bar Stool', 'Seating', 'EA', 28),
  ('SEA-1133', 'Bramble Solid-Beech Guest Chair', 'Seating', 'EA', 8),
  ('SEA-1150', 'Pemberton Mesh-Back Stacking Chair', 'Seating', 'EA', 11),
  ('SEA-1177', 'Verity Swivel Solid-Beech Bench Seat', 'Seating', 'EA', 13),
  ('SEA-1194', 'Northrop Task Chair', 'Seating', 'EA', 24),
  ('SEA-1210', 'Sable Two-Seat Sofa', 'Seating', 'EA', 15),
  ('SEA-1226', 'Ravensworth Bar Stool', 'Seating', 'EA', 11),
  ('SEA-1254', 'Verity Stackable Executive Chair', 'Seating', 'EA', 26),
  ('SEA-1265', 'Alder Swivel Executive Chair', 'Seating', 'EA', 30),
  ('SEA-1276', 'Northrop Brushed-Steel Lounge Chair', 'Seating', 'EA', 30),
  ('SEA-1285', 'Trentham Two-Seat Sofa', 'Seating', 'EA', 21),
  ('SEA-1303', 'Stanmore Slimline Brushed-Steel Two-Seat Sofa', 'Seating', 'EA', 25),
  ('SEA-1328', 'Trentham Moulded-Shell Bench Seat', 'Seating', 'EA', 10),
  ('SEA-1352', 'Ashgrove Armless Guest Chair', 'Seating', 'EA', 11),
  ('SEA-1386', 'Ashgrove Armless Bench Seat', 'Seating', 'EA', 13),
  ('SEA-1409', 'Cobalt Hill Low-Profile Mesh-Back Guest Chair', 'Seating', 'EA', 25),
  ('SEA-1426', 'Halden Armless Solid-Beech Two-Seat Sofa', 'Seating', 'EA', 22),
  ('SEA-1443', 'Northrop Stackable Stacking Chair', 'Seating', 'EA', 22),
  ('SEA-1467', 'Ashgrove Guest Chair', 'Seating', 'EA', 12),
  ('TAB-1017', 'Wexford Round Boardroom Table', 'Tables', 'EA', 6),
  ('TAB-1052', 'Stanmore Round Glass-Top Dining Table', 'Tables', 'EA', 6),
  ('TAB-1092', 'Bramble Side Table', 'Tables', 'EA', 6),
  ('TAB-1116', 'Wexford Compact Training Table', 'Tables', 'EA', 3),
  ('TAB-1139', 'Whitlock Height-Adjustable Boardroom Table', 'Tables', 'EA', 6),
  ('TAB-1161', 'Verity Side Table', 'Tables', 'EA', 4),
  ('TAB-1182', 'Ravensworth Round Glass-Top Dining Table', 'Tables', 'EA', 5),
  ('TAB-1209', 'Verity Conference Table', 'Tables', 'EA', 7),
  ('TAB-1224', 'Cobalt Hill Conference Table', 'Tables', 'EA', 6),
  ('TAB-1259', 'Kestrel Coffee Table', 'Tables', 'EA', 4),
  ('TAB-1287', 'Corbel Height-Adjustable Boardroom Table', 'Tables', 'EA', 5),
  ('TAB-1311', 'Bramble Occasional Table', 'Tables', 'EA', 6),
  ('TAB-1345', 'Stanmore Cafe Table', 'Tables', 'EA', 3),
  ('STO-1030', 'Whitlock Oak-Veneer Tambour Cupboard', 'Storage', 'EA', 14),
  ('STO-1067', 'Corbel Laminate-Top Bookcase', 'Storage', 'EA', 14),
  ('STO-1095', 'Corbel Compact Walnut-Finish Storage Cabinet', 'Storage', 'EA', 6),
  ('STO-1112', 'Kestrel Four-Drawer Storage Cabinet', 'Storage', 'EA', 13),
  ('STO-1138', 'Meridian Double-Sided Tambour Cupboard', 'Storage', 'EA', 8),
  ('STO-1152', 'Wexford Shelving Unit', 'Storage', 'EA', 14),
  ('STO-1159', 'Corbel Two-Drawer Credenza', 'Storage', 'EA', 11),
  ('STO-1195', 'Corbel Three-Drawer Walnut-Finish Credenza', 'Storage', 'EA', 13),
  ('STO-1210', 'Halden Four-Drawer Lateral File', 'Storage', 'EA', 11),
  ('STO-1227', 'Ashgrove Two-Drawer Mobile Pedestal', 'Storage', 'EA', 13),
  ('STO-1238', 'Wexford Lockable Wardrobe Unit', 'Storage', 'EA', 14),
  ('STO-1267', 'Wexford Open-Front Lateral File', 'Storage', 'EA', 5),
  ('STO-1293', 'Halden Double-Sided Walnut-Finish Wardrobe Unit', 'Storage', 'EA', 8),
  ('STO-1311', 'Sable Three-Drawer Credenza', 'Storage', 'EA', 10),
  ('STO-1337', 'Alder Open-Front Locker Bank', 'Storage', 'EA', 9),
  ('WRK-1029', 'Wexford Extended Felt-Panelled Compact Desk', 'Workstations', 'EA', 4),
  ('WRK-1069', 'Fenwick Double-Sided Sit-Stand Desk', 'Workstations', 'EA', 10),
  ('WRK-1079', 'Bramble Left-Hand Reception Counter', 'Workstations', 'EA', 12),
  ('WRK-1096', 'Trentham Double-Sided Walnut-Finish Sit-Stand Desk', 'Workstations', 'EA', 11),
  ('WRK-1109', 'Quillon Extended Walnut-Finish Corner Workstation', 'Workstations', 'EA', 10),
  ('WRK-1133', 'Fenwick Oak-Veneer Screen Panel', 'Workstations', 'EA', 7),
  ('WRK-1168', 'Alder Bench Desk', 'Workstations', 'EA', 6),
  ('WRK-1180', 'Larkspur Single-Bay Powder-Coated Return Unit', 'Workstations', 'EA', 11),
  ('WRK-1208', 'Fenwick Walnut-Finish Bench Desk', 'Workstations', 'EA', 10),
  ('WRK-1224', 'Trentham Double-Sided Screen Panel', 'Workstations', 'EA', 5),
  ('WRK-1252', 'Sable Corner Workstation', 'Workstations', 'EA', 8),
  ('WRK-1268', 'Bramble Double-Sided Return Unit', 'Workstations', 'EA', 11),
  ('WRK-1288', 'Larkspur Powder-Coated Screen Panel', 'Workstations', 'EA', 7),
  ('LGT-1034', 'Sable Desk Lamp', 'Lighting', 'EA', 27),
  ('LGT-1067', 'Pemberton Slimline Floor Lamp', 'Lighting', 'EA', 32),
  ('LGT-1103', 'Meridian Desk Lamp', 'Lighting', 'EA', 20),
  ('LGT-1110', 'Ravensworth Twin-Head Wall Sconce', 'Lighting', 'EA', 21),
  ('LGT-1117', 'Bramble Compact Wall Sconce', 'Lighting', 'EA', 11),
  ('LGT-1131', 'Stanmore Desk Lamp', 'Lighting', 'EA', 28),
  ('LGT-1145', 'Alder Clamp Light', 'Lighting', 'EA', 35),
  ('LGT-1162', 'Pemberton Pendant Light', 'Lighting', 'EA', 15),
  ('LGT-1195', 'Alder Pendant Light', 'Lighting', 'EA', 23),
  ('LGT-1226', 'Quillon Compact Desk Lamp', 'Lighting', 'EA', 16),
  ('LGT-1262', 'Ashgrove Matt-Black Task Lamp', 'Lighting', 'EA', 30),
  ('LGT-1296', 'Whitlock Low-Profile Matt-Black Pendant Light', 'Lighting', 'EA', 20),
  ('ACC-1037', 'Ravensworth Twin Moulded-Plastic Privacy Screen', 'Accessories', 'EA', 17),
  ('ACC-1072', 'Ashgrove Heavy-Duty Waste Bin', 'Accessories', 'EA', 50),
  ('ACC-1110', 'Kestrel Wide Whiteboard', 'Accessories', 'EA', 40),
  ('ACC-1134', 'Ashgrove Whiteboard', 'Accessories', 'EA', 43),
  ('ACC-1141', 'Wexford Cable Tray', 'Accessories', 'EA', 49),
  ('ACC-1154', 'Verity Moulded-Plastic Whiteboard', 'Accessories', 'EA', 32),
  ('ACC-1172', 'Alder Slimline Footrest', 'Accessories', 'EA', 19),
  ('ACC-1202', 'Cobalt Hill Heavy-Duty Moulded-Plastic Entrance Mat', 'Accessories', 'EA', 15),
  ('ACC-1217', 'Kestrel Wide Moulded-Plastic Privacy Screen', 'Accessories', 'EA', 40),
  ('ACC-1229', 'Ashgrove Wide Entrance Mat', 'Accessories', 'EA', 43),
  ('ACC-1248', 'Fenwick Adjustable Keyboard Tray', 'Accessories', 'EA', 28),
  ('ACC-1280', 'Stanmore Wide Keyboard Tray', 'Accessories', 'EA', 29),
  ('ACC-1306', 'Kestrel Compact Powder-Coated Coat Stand', 'Accessories', 'EA', 37),
  ('ACC-1342', 'Bramble Monitor Arm', 'Accessories', 'EA', 49),
  ('ACC-1375', 'Ravensworth Planter Box', 'Accessories', 'EA', 54)
ON CONFLICT (sku) DO NOTHING;

INSERT INTO public.inventory (sku, location, qty_on_hand, qty_committed, qty_incoming, incoming_eta, source, source_payload, updated_at) VALUES
  ('SEA-1016', 'default', 58, 25, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1016","location":"default","qty_on_hand":58,"qty_committed":25,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '295 minutes'),
  ('SEA-1046', 'default', 230, 33, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1046","location":"default","qty_on_hand":230,"qty_committed":33,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '270 minutes'),
  ('SEA-1061', 'default', 304, 92, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1061","location":"default","qty_on_hand":304,"qty_committed":92,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '186 minutes'),
  ('SEA-1096', 'default', 204, 16, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1096","location":"default","qty_on_hand":204,"qty_committed":16,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '272 minutes'),
  ('SEA-1133', 'default', 74, 19, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1133","location":"default","qty_on_hand":74,"qty_committed":19,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '88 minutes'),
  ('SEA-1150', 'default', 156, 7, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1150","location":"default","qty_on_hand":156,"qty_committed":7,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '68 minutes'),
  ('SEA-1177', 'default', 393, 19, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1177","location":"default","qty_on_hand":393,"qty_committed":19,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '223 minutes'),
  ('SEA-1194', 'default', 90, 46, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1194","location":"default","qty_on_hand":90,"qty_committed":46,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '117 minutes'),
  ('SEA-1210', 'default', 106, 29, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1210","location":"default","qty_on_hand":106,"qty_committed":29,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '207 minutes'),
  ('SEA-1226', 'default', 40, 15, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1226","location":"default","qty_on_hand":40,"qty_committed":15,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '138 minutes'),
  ('SEA-1254', 'default', 200, 115, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1254","location":"default","qty_on_hand":200,"qty_committed":115,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '69 minutes'),
  ('SEA-1265', 'default', 292, 69, 139, current_date + 42, 'quickbooks_stub', '{"sku":"SEA-1265","location":"default","qty_on_hand":292,"qty_committed":69,"qty_incoming":139,"incoming_eta":"+42d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '181 minutes'),
  ('SEA-1276', 'default', 205, 20, 26, current_date + 11, 'quickbooks_stub', '{"sku":"SEA-1276","location":"default","qty_on_hand":205,"qty_committed":20,"qty_incoming":26,"incoming_eta":"+11d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '128 minutes'),
  ('SEA-1285', 'default', 74, 30, 222, current_date + 7, 'quickbooks_stub', '{"sku":"SEA-1285","location":"default","qty_on_hand":74,"qty_committed":30,"qty_incoming":222,"incoming_eta":"+7d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '181 minutes'),
  ('SEA-1303', 'default', 85, 42, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1303","location":"default","qty_on_hand":85,"qty_committed":42,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '140 minutes'),
  ('SEA-1328', 'default', 157, 25, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1328","location":"default","qty_on_hand":157,"qty_committed":25,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '229 minutes'),
  ('SEA-1352', 'default', 96, 37, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1352","location":"default","qty_on_hand":96,"qty_committed":37,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '203 minutes'),
  ('SEA-1386', 'default', 371, 193, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1386","location":"default","qty_on_hand":371,"qty_committed":193,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '105 minutes'),
  ('SEA-1409', 'default', 161, 52, 205, current_date + 32, 'quickbooks_stub', '{"sku":"SEA-1409","location":"default","qty_on_hand":161,"qty_committed":52,"qty_incoming":205,"incoming_eta":"+32d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '170 minutes'),
  ('SEA-1426', 'default', 235, 107, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1426","location":"default","qty_on_hand":235,"qty_committed":107,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '5 minutes'),
  ('SEA-1443', 'default', 354, 34, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1443","location":"default","qty_on_hand":354,"qty_committed":34,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '105 minutes'),
  ('SEA-1467', 'default', 322, 157, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1467","location":"default","qty_on_hand":322,"qty_committed":157,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '111 minutes'),
  ('TAB-1017', 'default', 16, 6, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1017","location":"default","qty_on_hand":16,"qty_committed":6,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '237 minutes'),
  ('TAB-1052', 'default', 14, 0, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1052","location":"default","qty_on_hand":14,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '222 minutes'),
  ('TAB-1092', 'default', 25, 7, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1092","location":"default","qty_on_hand":25,"qty_committed":7,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '151 minutes'),
  ('TAB-1116', 'default', 36, 19, 133, current_date + 36, 'quickbooks_stub', '{"sku":"TAB-1116","location":"default","qty_on_hand":36,"qty_committed":19,"qty_incoming":133,"incoming_eta":"+36d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '246 minutes'),
  ('TAB-1139', 'default', 7, 1, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1139","location":"default","qty_on_hand":7,"qty_committed":1,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '160 minutes'),
  ('TAB-1161', 'default', 57, 14, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1161","location":"default","qty_on_hand":57,"qty_committed":14,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '48 minutes'),
  ('TAB-1182', 'default', 54, 25, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1182","location":"default","qty_on_hand":54,"qty_committed":25,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '22 minutes'),
  ('TAB-1209', 'default', 21, 9, 48, current_date + 30, 'quickbooks_stub', '{"sku":"TAB-1209","location":"default","qty_on_hand":21,"qty_committed":9,"qty_incoming":48,"incoming_eta":"+30d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '56 minutes'),
  ('TAB-1224', 'default', 2, 0, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1224","location":"default","qty_on_hand":2,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '62 minutes'),
  ('TAB-1259', 'default', 3, 1, 98, current_date + 25, 'quickbooks_stub', '{"sku":"TAB-1259","location":"default","qty_on_hand":3,"qty_committed":1,"qty_incoming":98,"incoming_eta":"+25d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '22 minutes'),
  ('TAB-1287', 'default', 18, 2, 48, current_date + 39, 'quickbooks_stub', '{"sku":"TAB-1287","location":"default","qty_on_hand":18,"qty_committed":2,"qty_incoming":48,"incoming_eta":"+39d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '45 minutes'),
  ('TAB-1311', 'default', 51, 19, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1311","location":"default","qty_on_hand":51,"qty_committed":19,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '119 minutes'),
  ('TAB-1345', 'default', 29, 11, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1345","location":"default","qty_on_hand":29,"qty_committed":11,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '259 minutes'),
  ('STO-1030', 'default', 84, 23, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1030","location":"default","qty_on_hand":84,"qty_committed":23,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '151 minutes'),
  ('STO-1067', 'default', 80, 14, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1067","location":"default","qty_on_hand":80,"qty_committed":14,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '196 minutes'),
  ('STO-1095', 'default', 6, 2, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1095","location":"default","qty_on_hand":6,"qty_committed":2,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1 minutes'),
  ('STO-1112', 'default', 113, 66, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1112","location":"default","qty_on_hand":113,"qty_committed":66,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '291 minutes'),
  ('STO-1138', 'default', 110, 62, 64, current_date + 30, 'quickbooks_stub', '{"sku":"STO-1138","location":"default","qty_on_hand":110,"qty_committed":62,"qty_incoming":64,"incoming_eta":"+30d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '14 minutes'),
  ('STO-1152', 'default', 58, 13, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1152","location":"default","qty_on_hand":58,"qty_committed":13,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '64 minutes'),
  ('STO-1159', 'default', 30, 8, 74, current_date + 38, 'quickbooks_stub', '{"sku":"STO-1159","location":"default","qty_on_hand":30,"qty_committed":8,"qty_incoming":74,"incoming_eta":"+38d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '62 minutes'),
  ('STO-1195', 'default', 140, 72, 51, current_date + 9, 'quickbooks_stub', '{"sku":"STO-1195","location":"default","qty_on_hand":140,"qty_committed":72,"qty_incoming":51,"incoming_eta":"+9d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '210 minutes'),
  ('STO-1210', 'default', 33, 9, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1210","location":"default","qty_on_hand":33,"qty_committed":9,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '8 minutes'),
  ('STO-1227', 'default', 30, 11, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1227","location":"default","qty_on_hand":30,"qty_committed":11,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '262 minutes'),
  ('STO-1238', 'default', 53, 19, 24, current_date + 44, 'quickbooks_stub', '{"sku":"STO-1238","location":"default","qty_on_hand":53,"qty_committed":19,"qty_incoming":24,"incoming_eta":"+44d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '213 minutes'),
  ('STO-1267', 'default', 124, 44, 172, current_date + 45, 'quickbooks_stub', '{"sku":"STO-1267","location":"default","qty_on_hand":124,"qty_committed":44,"qty_incoming":172,"incoming_eta":"+45d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '138 minutes'),
  ('STO-1293', 'default', 63, 9, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1293","location":"default","qty_on_hand":63,"qty_committed":9,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '228 minutes'),
  ('STO-1311', 'default', 47, 8, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1311","location":"default","qty_on_hand":47,"qty_committed":8,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '91 minutes'),
  ('STO-1337', 'default', 85, 50, 136, current_date + 25, 'quickbooks_stub', '{"sku":"STO-1337","location":"default","qty_on_hand":85,"qty_committed":50,"qty_incoming":136,"incoming_eta":"+25d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '127 minutes'),
  ('WRK-1029', 'default', 42, 17, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1029","location":"default","qty_on_hand":42,"qty_committed":17,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '205 minutes'),
  ('WRK-1069', 'default', 72, 3, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1069","location":"default","qty_on_hand":72,"qty_committed":3,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '156 minutes'),
  ('WRK-1079', 'default', 56, 23, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1079","location":"default","qty_on_hand":56,"qty_committed":23,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '290 minutes'),
  ('WRK-1096', 'default', 30, 8, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1096","location":"default","qty_on_hand":30,"qty_committed":8,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '294 minutes'),
  ('WRK-1109', 'default', 6, 3, 209, current_date + 34, 'quickbooks_stub', '{"sku":"WRK-1109","location":"default","qty_on_hand":6,"qty_committed":3,"qty_incoming":209,"incoming_eta":"+34d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '66 minutes'),
  ('WRK-1133', 'default', 24, 11, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1133","location":"default","qty_on_hand":24,"qty_committed":11,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '175 minutes'),
  ('WRK-1168', 'default', 46, 22, 222, current_date + 15, 'quickbooks_stub', '{"sku":"WRK-1168","location":"default","qty_on_hand":46,"qty_committed":22,"qty_incoming":222,"incoming_eta":"+15d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '288 minutes'),
  ('WRK-1180', 'default', 13, 7, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1180","location":"default","qty_on_hand":13,"qty_committed":7,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '52 minutes'),
  ('WRK-1208', 'default', 3, 2, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1208","location":"default","qty_on_hand":3,"qty_committed":2,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '44 minutes'),
  ('WRK-1224', 'default', 30, 10, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1224","location":"default","qty_on_hand":30,"qty_committed":10,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '153 minutes'),
  ('WRK-1252', 'default', 76, 4, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1252","location":"default","qty_on_hand":76,"qty_committed":4,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '50 minutes'),
  ('WRK-1268', 'default', 52, 30, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1268","location":"default","qty_on_hand":52,"qty_committed":30,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '97 minutes'),
  ('WRK-1288', 'default', 74, 39, 218, current_date + 17, 'quickbooks_stub', '{"sku":"WRK-1288","location":"default","qty_on_hand":74,"qty_committed":39,"qty_incoming":218,"incoming_eta":"+17d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '35 minutes'),
  ('LGT-1034', 'default', 79, 21, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1034","location":"default","qty_on_hand":79,"qty_committed":21,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '72 minutes'),
  ('LGT-1067', 'default', 73, 27, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1067","location":"default","qty_on_hand":73,"qty_committed":27,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '45 minutes'),
  ('LGT-1103', 'default', 258, 18, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1103","location":"default","qty_on_hand":258,"qty_committed":18,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '234 minutes'),
  ('LGT-1110', 'default', 57, 31, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1110","location":"default","qty_on_hand":57,"qty_committed":31,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '186 minutes'),
  ('LGT-1117', 'default', 112, 29, 203, current_date + 3, 'quickbooks_stub', '{"sku":"LGT-1117","location":"default","qty_on_hand":112,"qty_committed":29,"qty_incoming":203,"incoming_eta":"+3d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '26 minutes'),
  ('LGT-1131', 'default', 118, 8, 161, current_date + 31, 'quickbooks_stub', '{"sku":"LGT-1131","location":"default","qty_on_hand":118,"qty_committed":8,"qty_incoming":161,"incoming_eta":"+31d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '60 minutes'),
  ('LGT-1145', 'default', 164, 55, 22, current_date + 9, 'quickbooks_stub', '{"sku":"LGT-1145","location":"default","qty_on_hand":164,"qty_committed":55,"qty_incoming":22,"incoming_eta":"+9d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '234 minutes'),
  ('LGT-1162', 'default', 239, 32, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1162","location":"default","qty_on_hand":239,"qty_committed":32,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '66 minutes'),
  ('LGT-1195', 'default', 26, 4, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1195","location":"default","qty_on_hand":26,"qty_committed":4,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '140 minutes'),
  ('LGT-1226', 'default', 237, 65, 155, current_date + 38, 'quickbooks_stub', '{"sku":"LGT-1226","location":"default","qty_on_hand":237,"qty_committed":65,"qty_incoming":155,"incoming_eta":"+38d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '178 minutes'),
  ('LGT-1262', 'default', 195, 1, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1262","location":"default","qty_on_hand":195,"qty_committed":1,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '291 minutes'),
  ('LGT-1296', 'default', 239, 34, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1296","location":"default","qty_on_hand":239,"qty_committed":34,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '34 minutes'),
  ('ACC-1037', 'default', 481, 97, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1037","location":"default","qty_on_hand":481,"qty_committed":97,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '201 minutes'),
  ('ACC-1072', 'default', 225, 132, 178, current_date + 24, 'quickbooks_stub', '{"sku":"ACC-1072","location":"default","qty_on_hand":225,"qty_committed":132,"qty_incoming":178,"incoming_eta":"+24d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '72 minutes'),
  ('ACC-1110', 'default', 250, 61, 52, current_date + 28, 'quickbooks_stub', '{"sku":"ACC-1110","location":"default","qty_on_hand":250,"qty_committed":61,"qty_incoming":52,"incoming_eta":"+28d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '230 minutes'),
  ('ACC-1134', 'default', 464, 230, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1134","location":"default","qty_on_hand":464,"qty_committed":230,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '99 minutes'),
  ('ACC-1141', 'default', 548, 10, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1141","location":"default","qty_on_hand":548,"qty_committed":10,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '225 minutes'),
  ('ACC-1154', 'default', 334, 1, 190, current_date + 32, 'quickbooks_stub', '{"sku":"ACC-1154","location":"default","qty_on_hand":334,"qty_committed":1,"qty_incoming":190,"incoming_eta":"+32d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '149 minutes'),
  ('ACC-1172', 'default', 385, 178, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1172","location":"default","qty_on_hand":385,"qty_committed":178,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '198 minutes'),
  ('ACC-1202', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1202","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '107 minutes'),
  ('ACC-1217', 'default', 217, 10, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1217","location":"default","qty_on_hand":217,"qty_committed":10,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '283 minutes'),
  ('ACC-1229', 'default', 1, 0, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1229","location":"default","qty_on_hand":1,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '170 minutes'),
  ('ACC-1248', 'default', 539, 14, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1248","location":"default","qty_on_hand":539,"qty_committed":14,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '117 minutes'),
  ('ACC-1280', 'default', 107, 40, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1280","location":"default","qty_on_hand":107,"qty_committed":40,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '274 minutes'),
  ('ACC-1306', 'default', 372, 41, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1306","location":"default","qty_on_hand":372,"qty_committed":41,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '149 minutes'),
  ('ACC-1342', 'default', 587, 298, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1342","location":"default","qty_on_hand":587,"qty_committed":298,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '212 minutes'),
  ('ACC-1375', 'default', 350, 136, 62, current_date + 6, 'quickbooks_stub', '{"sku":"ACC-1375","location":"default","qty_on_hand":350,"qty_committed":136,"qty_incoming":62,"incoming_eta":"+6d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '210 minutes')
ON CONFLICT (sku, location) DO NOTHING;
