-- --------------------------------------------------------------------------
-- 0001_seed_catalogue.sql -- 90 catalogue SKUs across 6 categories
--
-- GENERATED FILE. Do not edit by hand -- edit scripts/generate-seed.mjs and re-run
-- `npm run seed:generate`. The generator is deterministic (mulberry32, fixed seed
-- 20260819), so regenerating produces byte-identical output.
--
-- Apply after migrations 0001-0012, in the Supabase SQL editor.
-- Every statement is ON CONFLICT DO NOTHING, so re-running is safe.
--
-- The 9000-block is reserved for the pinned fixtures in 0002 and never appears here.
--
-- Contains no credentials of any kind. Timestamps are relative expressions, so the data is
-- correctly aged whenever the file is applied.
-- --------------------------------------------------------------------------


INSERT INTO public.products (sku, name, category, uom, low_stock_threshold) VALUES
  ('SEA-1016', 'Whitlock Low-Profile Brushed-Steel Bar Stool', 'Seating', 'EA', 19),
  ('SEA-1029', 'Trentham Drafting Stool', 'Seating', 'EA', 13),
  ('SEA-1049', 'Northrop Heavy-Duty Side Chair', 'Seating', 'EA', 27),
  ('SEA-1086', 'Corbel Armless Guest Chair', 'Seating', 'EA', 18),
  ('SEA-1107', 'Fenwick Stackable Lounge Chair', 'Seating', 'EA', 27),
  ('SEA-1121', 'Sable Bench Seat', 'Seating', 'EA', 27),
  ('SEA-1153', 'Ashgrove Lounge Chair', 'Seating', 'EA', 19),
  ('SEA-1184', 'Whitlock Contoured Solid-Beech Bench Seat', 'Seating', 'EA', 27),
  ('SEA-1196', 'Sable Stacking Chair', 'Seating', 'EA', 22),
  ('SEA-1233', 'Corbel Task Chair', 'Seating', 'EA', 14),
  ('SEA-1243', 'Verity Powder-Coated Executive Chair', 'Seating', 'EA', 24),
  ('SEA-1253', 'Ashgrove Compact Stacking Chair', 'Seating', 'EA', 17),
  ('SEA-1280', 'Northrop Lounge Chair', 'Seating', 'EA', 18),
  ('SEA-1308', 'Whitlock Armless Powder-Coated Guest Chair', 'Seating', 'EA', 14),
  ('SEA-1347', 'Ashgrove Low-Profile Ottoman', 'Seating', 'EA', 23),
  ('SEA-1382', 'Stanmore Task Chair', 'Seating', 'EA', 16),
  ('SEA-1393', 'Larkspur Folding Two-Seat Sofa', 'Seating', 'EA', 23),
  ('SEA-1421', 'Pemberton Powder-Coated Executive Chair', 'Seating', 'EA', 10),
  ('SEA-1433', 'Bramble Slimline Brushed-Steel Bar Stool', 'Seating', 'EA', 27),
  ('SEA-1472', 'Alder Guest Chair', 'Seating', 'EA', 21),
  ('SEA-1508', 'Ravensworth Contoured Lounge Chair', 'Seating', 'EA', 13),
  ('SEA-1533', 'Sable Slimline Drafting Stool', 'Seating', 'EA', 19),
  ('TAB-1011', 'Stanmore Nesting Training Table', 'Tables', 'EA', 7),
  ('TAB-1026', 'Alder Modular Side Table', 'Tables', 'EA', 8),
  ('TAB-1038', 'Corbel Walnut-Finish Coffee Table', 'Tables', 'EA', 2),
  ('TAB-1065', 'Verity Conference Table', 'Tables', 'EA', 7),
  ('TAB-1094', 'Alder Glass-Top Cafe Table', 'Tables', 'EA', 4),
  ('TAB-1128', 'Larkspur Compact Dining Table', 'Tables', 'EA', 8),
  ('TAB-1140', 'Ashgrove Walnut-Finish Conference Table', 'Tables', 'EA', 4),
  ('TAB-1176', 'Quillon Coffee Table', 'Tables', 'EA', 8),
  ('TAB-1204', 'Stanmore Occasional Table', 'Tables', 'EA', 8),
  ('TAB-1234', 'Verity Wide Training Table', 'Tables', 'EA', 4),
  ('TAB-1262', 'Corbel Glass-Top Dining Table', 'Tables', 'EA', 3),
  ('TAB-1279', 'Kestrel Dining Table', 'Tables', 'EA', 5),
  ('TAB-1311', 'Ravensworth Glass-Top Boardroom Table', 'Tables', 'EA', 7),
  ('STO-1028', 'Kestrel Modular Lateral File', 'Storage', 'EA', 14),
  ('STO-1038', 'Sable Lockable Walnut-Finish Shelving Unit', 'Storage', 'EA', 13),
  ('STO-1073', 'Stanmore Tall Laminate-Top Tambour Cupboard', 'Storage', 'EA', 6),
  ('STO-1088', 'Sable Two-Drawer Credenza', 'Storage', 'EA', 5),
  ('STO-1126', 'Corbel Lockable Powder-Coated Locker Bank', 'Storage', 'EA', 12),
  ('STO-1133', 'Whitlock Powder-Coated Lateral File', 'Storage', 'EA', 13),
  ('STO-1173', 'Ravensworth Wide Brushed-Steel Wardrobe Unit', 'Storage', 'EA', 6),
  ('STO-1201', 'Trentham Walnut-Finish Lateral File', 'Storage', 'EA', 13),
  ('STO-1226', 'Sable Powder-Coated Wardrobe Unit', 'Storage', 'EA', 9),
  ('STO-1245', 'Ashgrove Modular Tambour Cupboard', 'Storage', 'EA', 11),
  ('STO-1260', 'Alder Bookcase', 'Storage', 'EA', 4),
  ('STO-1290', 'Verity Four-Drawer Credenza', 'Storage', 'EA', 14),
  ('STO-1314', 'Bramble Compact Locker Bank', 'Storage', 'EA', 6),
  ('STO-1347', 'Whitlock Four-Drawer Lateral File', 'Storage', 'EA', 6),
  ('STO-1369', 'Pemberton Three-Drawer Storage Cabinet', 'Storage', 'EA', 7),
  ('WRK-1012', 'Fenwick Felt-Panelled Return Unit', 'Workstations', 'EA', 6),
  ('WRK-1049', 'Ashgrove Laminate-Top Compact Desk', 'Workstations', 'EA', 10),
  ('WRK-1083', 'Wexford Extended Laminate-Top Bench Desk', 'Workstations', 'EA', 8),
  ('WRK-1115', 'Alder Powder-Coated Screen Panel', 'Workstations', 'EA', 4),
  ('WRK-1154', 'Bramble Right-Hand Felt-Panelled Screen Panel', 'Workstations', 'EA', 4),
  ('WRK-1191', 'Corbel Bench Desk', 'Workstations', 'EA', 9),
  ('WRK-1221', 'Pemberton Right-Hand Oak-Veneer Corner Workstation', 'Workstations', 'EA', 8),
  ('WRK-1257', 'Meridian Reception Counter', 'Workstations', 'EA', 7),
  ('WRK-1290', 'Cobalt Hill Powder-Coated Sit-Stand Desk', 'Workstations', 'EA', 7),
  ('WRK-1317', 'Ashgrove Left-Hand Walnut-Finish Bench Desk', 'Workstations', 'EA', 7),
  ('WRK-1357', 'Wexford Modular Screen Panel', 'Workstations', 'EA', 9),
  ('WRK-1397', 'Ravensworth Wide Powder-Coated Compact Desk', 'Workstations', 'EA', 6),
  ('WRK-1411', 'Kestrel Walnut-Finish Compact Desk', 'Workstations', 'EA', 8),
  ('LGT-1016', 'Wexford Wall Sconce', 'Lighting', 'EA', 31),
  ('LGT-1051', 'Stanmore Slimline Wall Sconce', 'Lighting', 'EA', 20),
  ('LGT-1091', 'Stanmore Twin-Head Task Lamp', 'Lighting', 'EA', 33),
  ('LGT-1099', 'Bramble Frosted-Glass Under-Shelf Light', 'Lighting', 'EA', 18),
  ('LGT-1124', 'Ravensworth Frosted-Glass Pendant Light', 'Lighting', 'EA', 15),
  ('LGT-1135', 'Whitlock Floor Lamp', 'Lighting', 'EA', 20),
  ('LGT-1147', 'Stanmore Under-Shelf Light', 'Lighting', 'EA', 31),
  ('LGT-1159', 'Stanmore Twin-Head Desk Lamp', 'Lighting', 'EA', 10),
  ('LGT-1178', 'Larkspur Brushed-Steel Under-Shelf Light', 'Lighting', 'EA', 30),
  ('LGT-1204', 'Corbel Wall Sconce', 'Lighting', 'EA', 17),
  ('LGT-1217', 'Meridian Slimline Clamp Light', 'Lighting', 'EA', 19),
  ('LGT-1236', 'Alder Frosted-Glass Task Lamp', 'Lighting', 'EA', 14),
  ('ACC-1031', 'Larkspur Brushed-Steel Whiteboard', 'Accessories', 'EA', 59),
  ('ACC-1068', 'Kestrel Powder-Coated Cable Tray', 'Accessories', 'EA', 43),
  ('ACC-1077', 'Sable Adjustable Footrest', 'Accessories', 'EA', 55),
  ('ACC-1112', 'Northrop Planter Box', 'Accessories', 'EA', 42),
  ('ACC-1127', 'Cobalt Hill Heavy-Duty Moulded-Plastic Monitor Arm', 'Accessories', 'EA', 20),
  ('ACC-1152', 'Bramble Heavy-Duty Footrest', 'Accessories', 'EA', 19),
  ('ACC-1170', 'Pemberton Compact Moulded-Plastic Monitor Arm', 'Accessories', 'EA', 44),
  ('ACC-1199', 'Fenwick Twin Felt-Panelled Cable Tray', 'Accessories', 'EA', 25),
  ('ACC-1215', 'Quillon Adjustable Brushed-Steel Privacy Screen', 'Accessories', 'EA', 58),
  ('ACC-1254', 'Meridian Compact Cable Tray', 'Accessories', 'EA', 20),
  ('ACC-1280', 'Bramble Compact Brushed-Steel Privacy Screen', 'Accessories', 'EA', 28),
  ('ACC-1292', 'Wexford Felt-Panelled Entrance Mat', 'Accessories', 'EA', 33),
  ('ACC-1327', 'Halden Modular Whiteboard', 'Accessories', 'EA', 51),
  ('ACC-1360', 'Bramble Wide Whiteboard', 'Accessories', 'EA', 58),
  ('ACC-1384', 'Sable Slimline Moulded-Plastic Privacy Screen', 'Accessories', 'EA', 20)
ON CONFLICT (sku) DO NOTHING;

INSERT INTO public.inventory (sku, location, qty_on_hand, qty_committed, qty_incoming, incoming_eta, source, source_payload, updated_at) VALUES
  ('SEA-1016', 'default', 368, 182, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1016","location":"default","qty_on_hand":368,"qty_committed":182,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '206 minutes'),
  ('SEA-1029', 'default', 314, 86, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1029","location":"default","qty_on_hand":314,"qty_committed":86,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '2646 minutes'),
  ('SEA-1049', 'default', 233, 25, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1049","location":"default","qty_on_hand":233,"qty_committed":25,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '186 minutes'),
  ('SEA-1086', 'default', 359, 118, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1086","location":"default","qty_on_hand":359,"qty_committed":118,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1114 minutes'),
  ('SEA-1107', 'default', 45, 7, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1107","location":"default","qty_on_hand":45,"qty_committed":7,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '3039 minutes'),
  ('SEA-1121', 'default', 198, 54, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1121","location":"default","qty_on_hand":198,"qty_committed":54,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '90 minutes'),
  ('SEA-1153', 'default', 9, 5, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1153","location":"default","qty_on_hand":9,"qty_committed":5,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '83 minutes'),
  ('SEA-1184', 'default', 12, 4, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1184","location":"default","qty_on_hand":12,"qty_committed":4,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '226 minutes'),
  ('SEA-1196', 'default', 36, 16, 117, current_date + 38, 'quickbooks_stub', '{"sku":"SEA-1196","location":"default","qty_on_hand":36,"qty_committed":16,"qty_incoming":117,"incoming_eta":"+38d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '289 minutes'),
  ('SEA-1233', 'default', 0, 0, 182, current_date + 44, 'quickbooks_stub', '{"sku":"SEA-1233","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":182,"incoming_eta":"+44d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '119 minutes'),
  ('SEA-1243', 'default', 11, 6, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1243","location":"default","qty_on_hand":11,"qty_committed":6,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '49 minutes'),
  ('SEA-1253', 'default', 21, 10, 165, current_date + 13, 'quickbooks_stub', '{"sku":"SEA-1253","location":"default","qty_on_hand":21,"qty_committed":10,"qty_incoming":165,"incoming_eta":"+13d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '29 minutes'),
  ('SEA-1280', 'default', 409, 218, 198, current_date + 45, 'quickbooks_stub', '{"sku":"SEA-1280","location":"default","qty_on_hand":409,"qty_committed":218,"qty_incoming":198,"incoming_eta":"+45d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '160 minutes'),
  ('SEA-1308', 'default', 347, 151, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1308","location":"default","qty_on_hand":347,"qty_committed":151,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '116 minutes'),
  ('SEA-1347', 'default', 0, 0, 150, current_date + 9, 'quickbooks_stub', '{"sku":"SEA-1347","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":150,"incoming_eta":"+9d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '280 minutes'),
  ('SEA-1382', 'default', 237, 119, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1382","location":"default","qty_on_hand":237,"qty_committed":119,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '26 minutes'),
  ('SEA-1393', 'default', 14, 7, 61, current_date + 42, 'quickbooks_stub', '{"sku":"SEA-1393","location":"default","qty_on_hand":14,"qty_committed":7,"qty_incoming":61,"incoming_eta":"+42d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '157 minutes'),
  ('SEA-1421', 'default', 6, 1, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1421","location":"default","qty_on_hand":6,"qty_committed":1,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '253 minutes'),
  ('SEA-1433', 'default', 444, 244, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1433","location":"default","qty_on_hand":444,"qty_committed":244,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '96 minutes'),
  ('SEA-1472', 'default', 264, 107, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1472","location":"default","qty_on_hand":264,"qty_committed":107,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '41 minutes'),
  ('SEA-1508', 'default', 211, 111, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1508","location":"default","qty_on_hand":211,"qty_committed":111,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '94 minutes'),
  ('SEA-1533', 'default', 262, 109, 0, NULL, 'quickbooks_stub', '{"sku":"SEA-1533","location":"default","qty_on_hand":262,"qty_committed":109,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '3338 minutes'),
  ('TAB-1011', 'default', 87, 52, 162, current_date + 22, 'quickbooks_stub', '{"sku":"TAB-1011","location":"default","qty_on_hand":87,"qty_committed":52,"qty_incoming":162,"incoming_eta":"+22d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '39 minutes'),
  ('TAB-1026', 'default', 0, 0, 90, current_date + 43, 'quickbooks_stub', '{"sku":"TAB-1026","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":90,"incoming_eta":"+43d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '215 minutes'),
  ('TAB-1038', 'default', 40, 23, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1038","location":"default","qty_on_hand":40,"qty_committed":23,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '22 minutes'),
  ('TAB-1065', 'default', 33, 5, 158, current_date + 10, 'quickbooks_stub', '{"sku":"TAB-1065","location":"default","qty_on_hand":33,"qty_committed":5,"qty_incoming":158,"incoming_eta":"+10d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1 minutes'),
  ('TAB-1094', 'default', 50, 19, 211, current_date + 24, 'quickbooks_stub', '{"sku":"TAB-1094","location":"default","qty_on_hand":50,"qty_committed":19,"qty_incoming":211,"incoming_eta":"+24d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '19 minutes'),
  ('TAB-1128', 'default', 29, 15, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1128","location":"default","qty_on_hand":29,"qty_committed":15,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '90 minutes'),
  ('TAB-1140', 'default', 65, 38, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1140","location":"default","qty_on_hand":65,"qty_committed":38,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '190 minutes'),
  ('TAB-1176', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1176","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '148 minutes'),
  ('TAB-1204', 'default', 2, 0, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1204","location":"default","qty_on_hand":2,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '140 minutes'),
  ('TAB-1234', 'default', 5, 2, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1234","location":"default","qty_on_hand":5,"qty_committed":2,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '196 minutes'),
  ('TAB-1262', 'default', 9, 0, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1262","location":"default","qty_on_hand":9,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1 minutes'),
  ('TAB-1279', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1279","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '294 minutes'),
  ('TAB-1311', 'default', 41, 22, 0, NULL, 'quickbooks_stub', '{"sku":"TAB-1311","location":"default","qty_on_hand":41,"qty_committed":22,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1392 minutes'),
  ('STO-1028', 'default', 90, 49, 12, current_date + 19, 'quickbooks_stub', '{"sku":"STO-1028","location":"default","qty_on_hand":90,"qty_committed":49,"qty_incoming":12,"incoming_eta":"+19d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '101 minutes'),
  ('STO-1038', 'default', 115, 40, 56, current_date + 19, 'quickbooks_stub', '{"sku":"STO-1038","location":"default","qty_on_hand":115,"qty_committed":40,"qty_incoming":56,"incoming_eta":"+19d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1283 minutes'),
  ('STO-1073', 'default', 17, 6, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1073","location":"default","qty_on_hand":17,"qty_committed":6,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '202 minutes'),
  ('STO-1088', 'default', 34, 17, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1088","location":"default","qty_on_hand":34,"qty_committed":17,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '192 minutes'),
  ('STO-1126', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1126","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '183 minutes'),
  ('STO-1133', 'default', 160, 82, 213, current_date + 28, 'quickbooks_stub', '{"sku":"STO-1133","location":"default","qty_on_hand":160,"qty_committed":82,"qty_incoming":213,"incoming_eta":"+28d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '213 minutes'),
  ('STO-1173', 'default', 67, 27, 113, current_date + 35, 'quickbooks_stub', '{"sku":"STO-1173","location":"default","qty_on_hand":67,"qty_committed":27,"qty_incoming":113,"incoming_eta":"+35d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '107 minutes'),
  ('STO-1201', 'default', 122, 67, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1201","location":"default","qty_on_hand":122,"qty_committed":67,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '4021 minutes'),
  ('STO-1226', 'default', 118, 59, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1226","location":"default","qty_on_hand":118,"qty_committed":59,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '2802 minutes'),
  ('STO-1245', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1245","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1556 minutes'),
  ('STO-1260', 'default', 53, 7, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1260","location":"default","qty_on_hand":53,"qty_committed":7,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '44 minutes'),
  ('STO-1290', 'default', 27, 10, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1290","location":"default","qty_on_hand":27,"qty_committed":10,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '98 minutes'),
  ('STO-1314', 'default', 87, 18, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1314","location":"default","qty_on_hand":87,"qty_committed":18,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1997 minutes'),
  ('STO-1347', 'default', 98, 27, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1347","location":"default","qty_on_hand":98,"qty_committed":27,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '58 minutes'),
  ('STO-1369', 'default', 85, 32, 0, NULL, 'quickbooks_stub', '{"sku":"STO-1369","location":"default","qty_on_hand":85,"qty_committed":32,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '239 minutes'),
  ('WRK-1012', 'default', 70, 19, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1012","location":"default","qty_on_hand":70,"qty_committed":19,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '44 minutes'),
  ('WRK-1049', 'default', 67, 36, 215, current_date + 16, 'quickbooks_stub', '{"sku":"WRK-1049","location":"default","qty_on_hand":67,"qty_committed":36,"qty_incoming":215,"incoming_eta":"+16d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '88 minutes'),
  ('WRK-1083', 'default', 0, 0, 125, current_date + 30, 'quickbooks_stub', '{"sku":"WRK-1083","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":125,"incoming_eta":"+30d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '194 minutes'),
  ('WRK-1115', 'default', 76, 25, 43, current_date + 24, 'quickbooks_stub', '{"sku":"WRK-1115","location":"default","qty_on_hand":76,"qty_committed":25,"qty_incoming":43,"incoming_eta":"+24d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '173 minutes'),
  ('WRK-1154', 'default', 0, 0, 113, current_date + 38, 'quickbooks_stub', '{"sku":"WRK-1154","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":113,"incoming_eta":"+38d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '8 minutes'),
  ('WRK-1191', 'default', 0, 0, 148, current_date + 32, 'quickbooks_stub', '{"sku":"WRK-1191","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":148,"incoming_eta":"+32d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '133 minutes'),
  ('WRK-1221', 'default', 0, 0, 71, current_date + 29, 'quickbooks_stub', '{"sku":"WRK-1221","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":71,"incoming_eta":"+29d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '45 minutes'),
  ('WRK-1257', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1257","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '247 minutes'),
  ('WRK-1290', 'default', 40, 23, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1290","location":"default","qty_on_hand":40,"qty_committed":23,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '4 minutes'),
  ('WRK-1317', 'default', 48, 1, 55, current_date + 23, 'quickbooks_stub', '{"sku":"WRK-1317","location":"default","qty_on_hand":48,"qty_committed":1,"qty_incoming":55,"incoming_eta":"+23d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '283 minutes'),
  ('WRK-1357', 'default', 45, 27, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1357","location":"default","qty_on_hand":45,"qty_committed":27,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '272 minutes'),
  ('WRK-1397', 'default', 92, 49, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1397","location":"default","qty_on_hand":92,"qty_committed":49,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '276 minutes'),
  ('WRK-1411', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"WRK-1411","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '31 minutes'),
  ('LGT-1016', 'default', 174, 76, 219, current_date + 22, 'quickbooks_stub', '{"sku":"LGT-1016","location":"default","qty_on_hand":174,"qty_committed":76,"qty_incoming":219,"incoming_eta":"+22d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '2905 minutes'),
  ('LGT-1051', 'default', 34, 18, 211, current_date + 44, 'quickbooks_stub', '{"sku":"LGT-1051","location":"default","qty_on_hand":34,"qty_committed":18,"qty_incoming":211,"incoming_eta":"+44d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '106 minutes'),
  ('LGT-1091', 'default', 121, 17, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1091","location":"default","qty_on_hand":121,"qty_committed":17,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '173 minutes'),
  ('LGT-1099', 'default', 0, 0, 162, current_date + 39, 'quickbooks_stub', '{"sku":"LGT-1099","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":162,"incoming_eta":"+39d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '55 minutes'),
  ('LGT-1124', 'default', 11, 3, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1124","location":"default","qty_on_hand":11,"qty_committed":3,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '64 minutes'),
  ('LGT-1135', 'default', 89, 42, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1135","location":"default","qty_on_hand":89,"qty_committed":42,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '155 minutes'),
  ('LGT-1147', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1147","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1 minutes'),
  ('LGT-1159', 'default', 9, 2, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1159","location":"default","qty_on_hand":9,"qty_committed":2,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '265 minutes'),
  ('LGT-1178', 'default', 22, 7, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1178","location":"default","qty_on_hand":22,"qty_committed":7,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '97 minutes'),
  ('LGT-1204', 'default', 25, 13, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1204","location":"default","qty_on_hand":25,"qty_committed":13,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '114 minutes'),
  ('LGT-1217', 'default', 199, 52, 51, current_date + 9, 'quickbooks_stub', '{"sku":"LGT-1217","location":"default","qty_on_hand":199,"qty_committed":52,"qty_incoming":51,"incoming_eta":"+9d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '168 minutes'),
  ('LGT-1236', 'default', 85, 44, 0, NULL, 'quickbooks_stub', '{"sku":"LGT-1236","location":"default","qty_on_hand":85,"qty_committed":44,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '650 minutes'),
  ('ACC-1031', 'default', 348, 200, 208, current_date + 19, 'quickbooks_stub', '{"sku":"ACC-1031","location":"default","qty_on_hand":348,"qty_committed":200,"qty_incoming":208,"incoming_eta":"+19d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '259 minutes'),
  ('ACC-1068', 'default', 614, 282, 62, current_date + 25, 'quickbooks_stub', '{"sku":"ACC-1068","location":"default","qty_on_hand":614,"qty_committed":282,"qty_incoming":62,"incoming_eta":"+25d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '1365 minutes'),
  ('ACC-1077', 'default', 304, 151, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1077","location":"default","qty_on_hand":304,"qty_committed":151,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '294 minutes'),
  ('ACC-1112', 'default', 89, 50, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1112","location":"default","qty_on_hand":89,"qty_committed":50,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '29 minutes'),
  ('ACC-1127', 'default', 248, 64, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1127","location":"default","qty_on_hand":248,"qty_committed":64,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '20 minutes'),
  ('ACC-1152', 'default', 625, 281, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1152","location":"default","qty_on_hand":625,"qty_committed":281,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '226 minutes'),
  ('ACC-1170', 'default', 426, 210, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1170","location":"default","qty_on_hand":426,"qty_committed":210,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '106 minutes'),
  ('ACC-1199', 'default', 2, 1, 83, current_date + 8, 'quickbooks_stub', '{"sku":"ACC-1199","location":"default","qty_on_hand":2,"qty_committed":1,"qty_incoming":83,"incoming_eta":"+8d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '43 minutes'),
  ('ACC-1215', 'default', 486, 137, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1215","location":"default","qty_on_hand":486,"qty_committed":137,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '228 minutes'),
  ('ACC-1254', 'default', 454, 160, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1254","location":"default","qty_on_hand":454,"qty_committed":160,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '129 minutes'),
  ('ACC-1280', 'default', 107, 16, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1280","location":"default","qty_on_hand":107,"qty_committed":16,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '70 minutes'),
  ('ACC-1292', 'default', 578, 237, 203, current_date + 45, 'quickbooks_stub', '{"sku":"ACC-1292","location":"default","qty_on_hand":578,"qty_committed":237,"qty_incoming":203,"incoming_eta":"+45d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '131 minutes'),
  ('ACC-1327', 'default', 0, 0, 0, NULL, 'quickbooks_stub', '{"sku":"ACC-1327","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":0,"incoming_eta":null,"source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '185 minutes'),
  ('ACC-1360', 'default', 0, 0, 133, current_date + 25, 'quickbooks_stub', '{"sku":"ACC-1360","location":"default","qty_on_hand":0,"qty_committed":0,"qty_incoming":133,"incoming_eta":"+25d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '299 minutes'),
  ('ACC-1384', 'default', 6, 3, 178, current_date + 27, 'quickbooks_stub', '{"sku":"ACC-1384","location":"default","qty_on_hand":6,"qty_committed":3,"qty_incoming":178,"incoming_eta":"+27d","source":"quickbooks_stub","note":"Synthetic stub payload. Shape mirrors what the adapter returns."}'::jsonb, now() - interval '55 minutes')
ON CONFLICT (sku, location) DO NOTHING;
